# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - dof_controller
    - grip_controller

  dof_controller:
    type: FollowJointTrajectory
    joints:
      - revolute_1
      - revolute_2
      - revolute_4
      - revolute_5
      - revolute_6
      - revolute_7
    action_ns: follow_joint_trajectory
    default: true
  grip_controller:
    type: FollowJointTrajectory
    joints:
      - revolute_8