# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    dof_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    grip_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

dof_controller:
  ros__parameters:
    joints:
      - revolute_1
      - revolute_2
      - revolute_4
      - revolute_5
      - revolute_6
      - revolute_7
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
grip_controller:
  ros__parameters:
    joints:
      - revolute_8
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true